name: deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mtsmachado8/heroku-deploy@v2.0.3
        with:
          api_key: ${{secrets.HEROKU_PASSWORD}}
          app_name: "testingapp009"
          email: ${{ secrets.HEROKU_USERNAME }}
          dockerfile_path: './'
