name: deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
        mvn test
        mvn verify
        mvn -B package --file pom.xml
        heroku login
        heroku plugins:install java
        heroku war:deploy "./target/reactServlet.war" --app egg-zam-app
