name: deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: |
          mvn test
          mvn verify
          mvn -B package --file pom.xml
  build:
    runs-on: ubuntu-latest
    needs: [verify]
    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker jsp-servlet-maven
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: ${{ secrets.DOCKER_USERNAME }}
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.DOCKER_PASSWORD }}
        # Docker repository to tag the image with
        repository: mayanktomar/react-servlet-maven
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: latest
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        dockerfile: ./Dockerfile
        # Comma-delimited list of images to consider as cache sources
        cache_froms: mayanktomar/react-servlet-maven:latest
