name: deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: |
          mvn test
          mvn verify
          mvn -B package --file pom.xml
  deploy:
    runs-on: ubuntu-latest
    needs: [verify]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: jctaveras/heroku-deploy@v1.0.0
        with:
          email: ${{ secrets.HEROKU_USERNAME }}
          api_key: ${{ secrets.HEROKU_PASSWORD }}
          app_name: mayankdemo
          dockerfile_path: './Dockerfile'
